### ISSUE TITLE
Feature Request: system wide screen on/off

### ISSUE THREAD

**Issue by shogun168** [92lleo/StayAwake#1]
Really liking this module, it'd be great if you could enable screen on function regardless of what app was in the foreground. i.e. you could move from app to app and it'll stay turned on until you press the key combination to go back to the 'normal' timeout state. Thanks!

**Comment by 92lleo** [comment]
Thanks for sharing feedback! I'll include this in the next version. Should be released between today and end of the week.

**Comment by shogun168** [comment]
Ah brilliant .. thanks for adding this in. I’m looking forward to being able to change the key combinations too as having the volume change and it beep is kind of irritating. Keep up the awesome work.

**Comment by 92lleo** [comment]
I have a preview version you can test if you want to. you can get it here (deleted link because of bugs) You can toggle per app with BACK+VOL-DOWN and systemwide per BACK+VOL-UP. Pressing the back key first prevents audio changes. I didnt want to completly overwrite the volume buttons, so they dont interfere with volume change. 

I'm working on setting different keys for the actions

**Comment by shogun168** [comment]
Nice! I’ll install it and give it a shot tonight. By the way, just food for thought, I’d recommend maybe not having any toggle action that includes holding the ‘back’ button down. On a lot of custom ROMs + developer mode, holding the ‘back’ button down results in killing (force quitting) any foreground application. 

Personally, I’d opt for maybe double tapping on the overview/menu button? Or maybe long pressing on the status bar? Just some ideas :)

**Comment by 92lleo** [comment]
That's right, the back button is just for testing, was the easiest to implement. Don't install the version I uploaded, it will brake the back button after some time. Just disable the module or uninstall and reinstall the version from xposed.
I'll look into this :)

**Comment by shogun168** [comment]
Haha, OK sure thing .. I’ll wait for your next xposed release. Thanks!

**Comment by 92lleo** [comment]
The last 10 days i tried some stuff so the volume change wont be triggered. But right now the only solution would be to overwrite the button which is not very useful. The only buttons that can be used are volume and back key right now, I was not able to hook home or recent key yet. Everything is easier when the screen is off, but thats not very useful either. Double clicking the navbar would only work for systemwide screen on, I'm trying to get it to work this way.
The next release will only be a cleaner release since many people are using this already, it won't fix this issue here. But be patient, I've not forgotten about this ;)

**Comment by shogun168** [comment]
Thanks for your continued work on this module. Unfortunately for this, I’ve found a different method of achieving what your app does by using Tasker. But, keep up the awesome work, I’m sure it’ll be invaluable to other users.

**Comment by 92lleo** [comment]
version 0.5.0 (commit 6d2966cb2e7abcdac2beab89b4d75bea65360f8d) adds partial support for systemwide screen on amongst other things.
I will work on a more user-friendly solution for this problem such as personalized activation methods/buttons.
